### ISSUE TITLE
Bump handlebars to 0.4?

### ISSUE THREAD

**Issue by senekor** [Manishearth/handlebars-fluent#10]
Hi there. I've been trying to update www.rust-lang.org to rocket 0.5 rc3. One problem I'm having (I think) is that rocket rc3 (actually the `rocket_dyn_templates` crate) requires handlebars 0.4. This crate depends on 0.2. I'm getting type errors when registering the helpers:

```rust
engine
    .handlebars
    .register_helper("fluent", Box::new(FluentHelper::new(create_loader())));
```

> required for `handlebars_fluent::FluentHelper<handlebars_fluent::SimpleLoader>` to implement `handlebars::HelperDef`

I think this is because there are two incompatible copies of that trait, one from handlebars 0.2 and one from handlebars 0.4.

Would it be much work to release a version of this crate compatible with handlebars 0.4?

**Comment by Manishearth** [comment]
I'd accept a PR that does this
