### ISSUE TITLE
Publish handlebars v5 support

### ISSUE THREAD

**Issue by dtolnay** [Manishearth/handlebars-fluent#14]
Would it be possible to get https://github.com/Manishearth/handlebars-fluent/pull/13 published to crates.io? Thanks!

**Comment by Manishearth** [comment]
Done, v0.4.0

**Comment by dtolnay** [comment]
Something went wrong, I don't see 0.4.0 on crates.io. Separately, master is currently 0462000574a7222ff6541cb4380c6be56ab3ae1e which is still version 0.3.2, and there is no v0.4.0 tag.

<img src="https://github.com/Manishearth/handlebars-fluent/assets/1940490/d1fb1877-d651-4343-a259-e4cf4dcafc82" width="600">

**Comment by Manishearth** [comment]
yeah had a little hiccup since I'm not on my main programming computer right now. fixed
