### ISSUE TITLE
Would switching to to fluent-templates make sense?

### ISSUE THREAD

**Issue by alerque** [Manishearth/handlebars-fluent#9]
I just recently started adding Fluent support to a [Tera CLI](https://github.com/chevdor/tera-cli/issues/20) using the [`fluent_templates` crate](https://docs.rs/fluent-templates/0.8.0/fluent_templates/). While working on #8 here I noticed it will take some refactoring to use newer Fluent bundle & Unicode crates and before even attempting that work I wondered what the reason was this isn't using `fluent_templates`. I realize the answer is probably "it didn't exist whet this was made", but going forward might it make sense to switch gears?

**Comment by Manishearth** [comment]
It seems like that crate already has its own handlebars integration: I don't really see the point to depending on that if it does that? It seems more like an alternative than a component.
